export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  CITY_ADMIN = 'CITY_ADMIN',
  CITIZEN = 'CITIZEN'
}

export enum IssueStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED'
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  phone?: string;
  city?: string; // For City Admins and Citizens
  state?: string;
  address?: string;
  createdAt: number;
}

export interface Issue {
  id: string;
  title: string;
  description: string;
  status: IssueStatus;
  category: string;
  latitude?: number;
  longitude?: number;
  address: string;
  imageUrl?: string;
  authorId: string;
  authorName: string;
  city: string;
  createdAt: number;
  updatedAt: number;
  aiSummary?: string; // Generated by Gemini
}

export interface AuthState {
  user: User | null;
  isAuthenticated: boolean;
  loading: boolean;
}

export interface CityStats {
  totalIssues: number;
  pending: number;
  inProgress: number;
  resolved: number;
}
